apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    project: node-selector-roboshop
spec:
  containers:
  - name: nginx
    image: nginx
  hostselector:
    project: roboshop